//add links to your pages here
export const pageLinks = [{ id: 1, href: "/", text: "home" }];

export const seeAlsoData = [
  {
    id: 1,
    title: "Slush 2025 – Europe’s Premier Startup Event",
    description:
      "Experience one of the world’s leading startup gatherings where founders, investors, and innovators meet in Helsinki’s Messukeskus.",
    date: "30 Nov – 1 Dec 2025",
    location: "Messukeskus, Helsinki",
    link: "https://www.slush.org/",
    image:
      "https://www.munich-startup.de/wp-content/uploads/2018/12/Slush_2018_c_Jussi_Hellsten_734354.jpg",
  },
  {
    id: 2,
    title: "Helsinki Christmas Market (Tuomaan Markkinat)",
    description:
      "Step into the magic of the oldest outdoor Christmas market in Finland. Discover Finnish design, crafts, and festive treats at Senate Square.",
    date: "28 Nov – 22 Dec 2025",
    location: "Senate Square, Helsinki",
    link: "https://tuomaanmarkkinat.fi/en/",
    image:
      "https://tuomaanmarkkinat.fi/app/uploads/sites/2/2024/04/2023_Tuomaan_Markkinat_Print-78-1024x683.jpg",
  },
  {
    id: 3,
    title: "Finland’s Independence Day Celebrations",
    description:
      "Join the Finnish people as they celebrate their Independence Day with parades, candle-lit windows, and ceremonies throughout Helsinki.",
    date: "6 Dec 2025",
    location: "Across Helsinki",
    link: "https://www.myhelsinki.fi/en/see-and-do/events",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/37/Suomi100_University_of_Helsinki_main_building_3.jpg",
  },
  {
    id: 4,
    title: "Flow Festival 2025",
    description:
      "One of Europe’s most loved urban music and arts festivals returns to Helsinki with an incredible lineup of international artists.",
    date: "8–10 Aug 2025",
    location: "Suvilahti, Helsinki",
    link: "https://www.flowfestival.com/",
    image:
      "https://www.flowfestival.com/uploads/2025/09/Flow_Friday_2025_c_Petri_Anttila__Koptercam_DJI_etusivu.jpg",
  },
  {
    id: 5,
    title: "Helsinki Festival 2025",
    description:
      "Finland’s largest arts festival fills the city with performances, concerts, exhibitions, and immersive cultural experiences.",
    date: "15 Aug – 31 Aug 2025",
    location: "Various venues, Helsinki",
    link: "https://helsinginjuhlaviikot.fi/en/",
    image:
      "https://helsinkifestival.fi/app/uploads/sites/8/2021/06/36867344625_2a8cfb6ae1_o-1-1440x960.jpg",
  },
  {
    id: 6,
    title: "Lux Helsinki 2026",
    description:
      "Light installations illuminate Helsinki’s winter nights as artists transform familiar landmarks into glowing masterpieces.",
    date: "3–7 Jan 2026",
    location: "City centre, Helsinki",
    link: "https://luxhelsinki.fi/en/",
    image:
      "https://luxhelsinki.fi/app/uploads/sites/5/2025/01/Lux_Helsinki_2025_c_Petri_Anttila_E3A1502-Enhanced-NR_web-720x360.jpg",
  },
];

export const events = [
  {
    id: 1,
    city: "Helsinki",
    name: "Helsinki Christmas Market – Senate Square",
    category: "Family",
    description:
      "Finland’s oldest outdoor Christmas market with artisan stalls, festive food and a vintage carousel under Helsinki Cathedral.",
    date: "1 Dec – 22 Dec 2025",
    location: "Senate Square, Helsinki",
    image:
      "https://tuomaanmarkkinat.fi/app/uploads/sites/2/2024/04/2023_Tuomaan_Markkinat_Print-78-1024x683.jpg",
    tags: ["Christmas", "Outdoor"],
  },
  {
    id: 2,
    city: "Helsinki",
    name: "World Village Festival",
    category: "Art & Culture",
    description:
      "A free, vibrant multicultural festival in Helsinki showcasing music, theatre, dance and food from around the world.",
    date: "May 2026",
    location: "Helsinki",
    image:
      "https://www.helsinki.com/media/public/ketki/World%20Village%20Festival.jpg",
    tags: ["Multicultural", "Outdoor"],
  },
  {
    id: 3,
    city: "Espoo",
    name: "PianoEspoo Festival",
    category: "Art & Culture",
    description:
      "Renowned piano music festival in Espoo featuring top international pianists and young Finnish talents.",
    date: "19 Sept – 5 Oct 2025",
    location: "Espoo",
    image:
      "https://www.visitespoo.fi/sites/default/files/styles/1_1_s/public/2025-09/550660845_18519453604053277_8756413863435097288_n%20%281%29.jpg?h=8296598c&itok=71pWqMkS",
    tags: "Classical Music, Indoor",
  },
  {
    id: 4,
    city: "Espoo",
    name: "Weekend Festival Espoo",
    category: "Music",
    description:
      "One of the summer’s biggest electronic-music festivals held at Vermo Arena in Espoo – top DJs, festival vibes, fun outdoors.",
    date: "1-2 Aug 2025",
    location: "Vermo Arena, Espoo",
    image:
      "https://www.visitespoo.fi/sites/default/files/styles/1_1_s/public/2025-04/WKND_Day1_221249_HenriJuvonen_6403-768x512%20%281%29.jpg?h=8296598c&itok=fYHkM3of",
    tags: ["Electronic Music", "Outdoor"],
  },
  {
    id: 5,
    city: "Vantaa",
    name: "BRQ Vantaa Festival",
    category: "Music",
    description:
      "Classical and baroque music festival in Vantaa, with concerts in historic churches and modern venues.",
    date: "8–14 Aug 2026",
    location: "Vantaa",
    image:
      "https://festivals.fi/wp-content/uploads/2013/04/BRQ-Vantaa-Festival-photo-Vantaan-Fotokerho-Eero-Kukkonen-1-913x515.jpeg",
    tags: ["Classical Music", "Indoor"],
  },
  {
    id: 6,
    city: "Vantaa",
    name: "Arctic Open Badminton Tournament",
    category: "Sports",
    description:
      "Top-level international badminton tournament held at Energia Areena, Vantaa – world-tour level players compete.",
    date: "7–12 Oct 2025",
    location: "Energia Areena, Vantaa",
    image:
      "https://www.arcticopen.fi/site/assets/files/1173/20210924_1912_sudirmancup2021_bprs1949-2.2000x700-u1i0s1q90f1t450l748z0.jpg",
    tags: ["Badminton", "Indoor"],
  },
  {
    id: 7,
    city: "Helsinki",
    name: "Helsinki Music Festival",
    category: "Music",
    description:
      "Annual classical music festival featuring international artists",
    date: "2025-12-15",
    location: "Helsinki Music Centre",
    image: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=400",
    tags: ["Music", "Outdoor"],
  },
  {
    id: 8,
    city: "Helsinki",
    name: "Art Exhibition: Nordic Lights",
    category: "Art",
    description: "Contemporary art exhibition showcasing Nordic artists",
    date: "2025-12-20",
    location: "Kiasma Museum",
    image: "https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=400",
    tags: ["Art", "Indoor"],
  },
  {
    id: 9,
    city: "Helsinki",
    name: "Winter Food Market",
    category: "Food",
    description: "Traditional Finnish winter delicacies and local crafts",
    date: "2025-12-10",
    location: "Old Market Hall",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    tags: ["Food", "Indoor", "Christmas"],
  },
  {
    id: 10,
    city: "Helsinki",
    name: "Tech Meetup Helsinki",
    category: "Technology",
    description: "Monthly gathering for tech enthusiasts and developers",
    date: "2025-12-18",
    location: "Maria 01 Startup Campus",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400",
    tags: ["Technology", "Indoor"],
  },
  {
    id: 11,
    city: "Helsinki",
    name: "Jazz Night at Storyville",
    category: "Music",
    description:
      "Evening of smooth jazz with local and international performers",
    date: "2025-12-22",
    location: "Storyville Jazz Club",
    image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=400",
    tags: ["Music", "Indoor"],
  },
  {
    id: 12,
    city: "Helsinki",
    name: "Finnish Design Week",
    category: "Art",
    description:
      "Celebrate Finnish design heritage and contemporary innovations",
    date: "2025-12-08",
    location: "Design Museum Helsinki",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    tags: ["Art", "Indoor"],
  },
  {
    id: 13,
    city: "Helsinki",
    name: "Winter Sports Festival",
    category: "Sports",
    description: "Exciting winter sports demonstrations and competitions",
    date: "2025-12-12",
    location: "Olympic Stadium",
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400",
    tags: ["Sports", "Outdoor"],
  },
  {
    id: 14,
    city: "Helsinki",
    name: "Helsinki Book Fair",
    category: "Culture",
    description:
      "Annual book fair featuring authors, publishers, and literature lovers",
    date: "2025-12-16",
    location: "Messukeskus",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
    tags: ["Culture", "Indoor"],
  },
  {
    id: 15,
    city: "Helsinki",
    name: "Electronic Music Night",
    category: "Music",
    description:
      "Underground electronic music event with local and international DJs",
    date: "2025-12-19",
    location: "Korjaamo",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400",
    tags: ["Music", "Indoor"],
  },
  {
    id: 16,
    city: "Helsinki",
    name: "Photography Exhibition",
    category: "Art",
    description: "Contemporary photography from Nordic photographers",
    date: "2025-12-14",
    location: "Helsinki Art Museum",
    image: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=400",
    tags: ["Art", "Indoor"],
  },
  {
    id: 17,
    city: "Helsinki",
    name: "Startup Pitch Night",
    category: "Technology",
    description: "Watch promising startups pitch their ideas to investors",
    date: "2025-12-21",
    location: "Slush HQ",
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400",
    tags: ["Technology", "Indoor"],
  },
  {
    id: 18,
    city: "Helsinki",
    name: "Comedy Show",
    category: "Entertainment",
    description:
      "Stand-up comedy night featuring Finnish and international comedians",
    date: "2025-12-17",
    location: "Apollo Live Club",
    image: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=400",
    tags: ["Entertainment", "Indoor"],
  },
  {
    id: 19,
    city: "Helsinki",
    name: "Yoga & Wellness Fair",
    category: "Wellness",
    description: "Wellness workshops, yoga sessions, and healthy living expo",
    date: "2025-12-11",
    location: "Allas Sea Pool",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
    tags: ["Wellness", "Indoor"],
  },
  {
    id: 20,
    city: "Helsinki",
    name: "Rock Concert",
    category: "Music",
    description: "Live rock concert featuring popular Finnish rock bands",
    date: "2025-12-23",
    location: "Tavastia",
    image: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=400",
    tags: ["Music", "Indoor"],
  },
  {
    id: 21,
    city: "Helsinki",
    name: "Gaming Tournament",
    category: "Gaming",
    description: "E-sports tournament with prizes and live streaming",
    date: "2025-12-13",
    location: "Assembly Hall",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400",
    tags: ["Gaming", "Indoor"],
  },
  {
    id: 22,
    city: "Helsinki",
    name: "New Year Gala",
    category: "Festival",
    description: "Elegant New Year celebration with dinner and live music",
    date: "2025-12-31",
    location: "Finlandia Hall",
    image: "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=400",
    tags: ["Festival", "Indoor"],
  },
  {
    id: 23,
    city: "Helsinki",
    name: "Film Festival",
    category: "Film",
    description: "Independent film screenings and director Q&A sessions",
    date: "2025-12-09",
    location: "Bio Rex",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400",
    tags: ["Film", "Indoor"],
  },
];
